### ISSUE TITLE
Installing Gulp4 breaks run-sequence

### ISSUE THREAD

**Issue by paymonyau** [OverZealous/run-sequence#104]
[13:43:40] TypeError: gulp.hasTask is not a function
    at /var/www/thesmalls/node_modules/run-sequence/index.js:23:22
    at Array.forEach (<anonymous>)
    at verifyTaskSets (/var/www/thesmalls/node_modules/run-sequence/index.js:17:11)
    at runSequence (/var/www/thesmalls/node_modules/run-sequence/index.js:130:2)
    at /var/www/thesmalls/gulpfile.js:30:12
    at taskWrapper (/var/www/thesmalls/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at asyncRunner (/var/www/thesmalls/node_modules/async-done/index.js:55:18)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

**Comment by paymonyau** [comment]
installing gulp4-run-sequence
