### ISSUE TITLE
strange error handling in nested run-sequence

### ISSUE THREAD

**Issue by ntopia** [OverZealous/run-sequence#36]
In normal case, nested run-sequence works good.
[source code]
```
var gulp = require('gulp');
var runSeq = require('run-sequence');
gulp.task('task-inner', function () {
	// do nothing
});
gulp.task('task2', function (cb) {
	runSeq('task-inner', cb);
});
gulp.task('task1', function (cb) {
	runSeq('task2', cb);
});
gulp.task('default', function (cb) {
	runSeq('task1', cb);
});
```
[output]
```
[17:22:15] Using gulpfile ~\xxx\gulpfile.js
[17:22:15] Starting 'default'...
[17:22:15] Starting 'task1'...
[17:22:15] Starting 'task2'...
[17:22:15] Starting 'task-inner'...
[17:22:15] Finished 'task-inner' after 58 μs
[17:22:15] Finished 'task2' after 904 μs
[17:22:15] Finished 'task1' after 1.54 ms
[17:22:15] Finished 'default' after 2.89 ms
```

When 'task-inner' throws an error, it prints strange long error messages.
This is just simplified case. I'm in trouble with some async plugins when it occurs some errors.
[source code]
```
var gulp = require('gulp');
var runSeq = require('run-sequence');
gulp.task('task-inner', function () {
	throw new Error('error');
});
gulp.task('task2', function (cb) {
	runSeq('task-inner', cb);
});
gulp.task('task1', function (cb) {
	runSeq('task2', cb);
});
gulp.task('default', function (cb) {
	runSeq('task1', cb);
});
```
[output]
```
[17:22:26] Using gulpfile ~\xxx\gulpfile.js
[17:22:26] Starting 'default'...
[17:22:26] Starting 'task1'...
[17:22:26] Starting 'task2'...
[17:22:26] Starting 'task-inner'...
[17:22:26] 'task-inner' errored after 75 μs
[17:22:26] Error: error
    at Gulp.<anonymous> (xxx\gulpfile.js:5:8)
    at module.exports (xxx\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (xxx\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (xxx\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (xxx\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at runNextSet (xxx\node_modules\run-sequence\index.js:79:16)
    at runSequence (xxx\node_modules\run-sequence\index.js:90:2)
    at Gulp.<anonymous> (xxx\gulpfile.js:9:2)
    at module.exports (xxx\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (xxx\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
[17:22:26] 'default' errored after 4.24 ms
[17:22:26] Error: [object Object]
    at formatError (xxx\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (xxx\node_modules\gulp\bin\gulp.js:195:15)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (xxx\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
    at xxx\node_modules\gulp\node_modules\orchestrator\index.js:275:23
    at finish (xxx\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (xxx\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
    at finish (xxx\node_modules\run-sequence\index.js:53:5)
    at Gulp.onError (xxx\node_modules\run-sequence\index.js:60:4)
    at Gulp.emit (events.js:129:20)
[17:22:26] 'task1' errored after 3.7 ms
[17:22:26] Error: [object Object]
    at formatError (xxx\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (xxx\node_modules\gulp\bin\gulp.js:195:15)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (xxx\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
    at xxx\node_modules\gulp\node_modules\orchestrator\index.js:275:23
    at finish (xxx\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (xxx\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
    at finish (xxx\node_modules\run-sequence\index.js:53:5)
    at Gulp.onError (xxx\node_modules\run-sequence\index.js:60:4)
    at Gulp.emit (events.js:129:20)
[17:22:26] 'task2' errored after 3.92 ms
[17:22:26] Error: [object Object]
    at formatError (xxx\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (xxx\node_modules\gulp\bin\gulp.js:195:15)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (xxx\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
    at xxx\node_modules\gulp\node_modules\orchestrator\index.js:275:23
    at finish (xxx\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (xxx\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
    at finish (xxx\node_modules\run-sequence\index.js:53:5)
    at Gulp.onError (xxx\node_modules\run-sequence\index.js:60:4)
    at Gulp.emit (events.js:129:20)
[17:22:26] 'task2' errored after 4.4 ms
[17:22:26] Error: [object Object]
    at formatError (xxx\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (xxx\node_modules\gulp\bin\gulp.js:195:15)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (xxx\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
    at xxx\node_modules\gulp\node_modules\orchestrator\index.js:275:23
    at finish (xxx\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (xxx\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
    at finish (xxx\node_modules\run-sequence\index.js:53:5)
    at Gulp.onError (xxx\node_modules\run-sequence\index.js:60:4)
    at Gulp.emit (events.js:129:20)
[17:22:26] 'task1' errored after 5.14 ms
[17:22:26] Error: [object Object]
    at formatError (xxx\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (xxx\node_modules\gulp\bin\gulp.js:195:15)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (xxx\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
    at xxx\node_modules\gulp\node_modules\orchestrator\index.js:275:23
    at finish (xxx\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (xxx\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
    at finish (xxx\node_modules\run-sequence\index.js:53:5)
    at Gulp.onError (xxx\node_modules\run-sequence\index.js:60:4)
    at Gulp.emit (events.js:129:20)
[17:22:26] 'task2' errored after 5.34 ms
[17:22:26] Error: [object Object]
    at formatError (xxx\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (xxx\node_modules\gulp\bin\gulp.js:195:15)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (xxx\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
    at xxx\node_modules\gulp\node_modules\orchestrator\index.js:275:23
    at finish (xxx\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (xxx\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
    at finish (xxx\node_modules\run-sequence\index.js:53:5)
    at Gulp.onError (xxx\node_modules\run-sequence\index.js:60:4)
    at Gulp.emit (events.js:129:20)
```

Here is my dev environment.
  * Windows 8.1 64bit
  * nodejs x64 v0.12.5
  * gulp 3.9.0 & run-sequence 1.1.1

Thank you.

**Comment by OverZealous** [comment]
I have no idea what your issue here is.  If you throw an error, the call stack prints an error.  `run-sequence` does not do anything with error handling.  It simply starts the requested gulp tasks.

**Comment by ntopia** [comment]
Yes you're right, but the error message is too long. Don't you think?
" 'task2' errored " is appeared 3 times. I wonder why.

**Comment by pixelshaded** [comment]
I am also seeing this. Error: [object Object] was sort of a give away that something isn't getting handled quite right. Essentially, if a child node in a task tree errors, we are seeing an error and stack trace for each parent for that child. I don't think this is necesary and in the examples posted by ntopia, you can see how much noise that generates. I should see the plugin error / thrown error, maybe a single stack trace, and then the list of parent tasks that failed. Thats it.

**Comment by OverZealous** [comment]
@pixelshaded As I said, `run-sequence` does not perform any error handling, it just passes the errors through to the callback.  If you would like to submit a PR, I'd be happy to look at it.  Otherwise, the use case above is very abnormal.

`run-sequence` isn't a replacement for the built-in task dependencies, it's intended to work alongside them.

**Comment by pixelshaded** [comment]
Debugging, run sequence uses the same gulp events that gulp uses. I.E. on("task_error"). So gulp gets this event first. This is where we get our properly formatted message. Run sequence then gets this event and destroys its listeners. If you passed run sequence a callback, it will run it with the error object. Gulp then handles the error a second time, but this time the error is wrapped in another error which is why you get Error: [object Object] when it tries to format it.

**Comment by pixelshaded** [comment]
So if you look at what orchestrator does with the error:

```
Orchestrator.prototype._emitTaskDone = function (task, message, err) {
		if (!task.args) {
			task.args = {task:task.name};
		}
		task.args.duration = task.duration;
		task.args.hrDuration = task.hrDuration;
		task.args.message = task.name+' '+message;
		var evt = 'stop';
		if (err) {
			task.args.err = err;
			evt = 'err';
		}
		// 'task_stop' or 'task_err'
		this.emit('task_'+evt, task.args);
	};
```

Run sequence should actually pass err.err to the callback instead of err.

**Comment by pixelshaded** [comment]
https://github.com/OverZealous/run-sequence/pull/39

**Comment by pixelshaded** [comment]
This of course won't fix the stack trace issue.
```
// Format orchestrator errors
function formatError(e) {
  if (!e.err) {
    return e.message;
  }

  // PluginError
  if (typeof e.err.showStack === 'boolean') {
    return e.err.toString();
  }

  // Normal error
  if (e.err.stack) {
    return e.err.stack;
  }

  // Unknown (string, number, etc.)
  return new Error(String(e.err)).stack;
}
```
If its not a plugin error, gulp will log the stack.

**Comment by OverZealous** [comment]
Thanks for the PR.  (I don't think it's `run-sequence`'s responsibility to narrow down the stack, because it might be hiding something that helps debugs the issue.)

**Comment by OverZealous** [comment]
The `[Object object]` error is fixed with #39, but `run-sequence` is not going to handle the nested errors at this time.

**Comment by pixelshaded** [comment]
We can't prevent gulp from re-logging since we need to tell it to end a task and that the task ended because of a failure. We can at least shorten the output and indicate which task cause the failure.

https://github.com/OverZealous/run-sequence/pull/40

**Comment by pixelshaded** [comment]
This is an example output with the pull request's changes
```
[12:16:13] Using gulpfile c:\repo\IgnitionOne\stable\prototype-coresettings\gulpfile.js
[12:16:13] Starting 'ts'...
[12:16:13] Starting 'automateTypescript'...
[12:16:13] Starting 'tsconfig'...
[12:16:13] No change to tsconfig.json required.
[12:16:13] Finished 'tsconfig' after 66 ms
[12:16:13] Starting 'tslint'...
[12:16:16] [gulp-tslint] error (no-var-keyword) c:\repo\IgnitionOne\stable\prototype-coresettings\src\server\main.ts[124, 1]: use of the var-keyword is disallowed, use 'let' or 'const' instead
[12:16:17] 'tslint' errored after 3.77 s
[12:16:17] Error in plugin 'gulp-tslint'
Message:
    Failed to lint: main.ts[124, 1]: use of the var-keyword is disallowed, use 'let' or 'const' instead.
[12:16:17] 'ts' errored after 3.87 s
[12:16:17] Error in plugin 'run-sequence'
Message:
    An error occured in task "tslint".
[12:16:17] 'automateTypescript' errored after 3.87 s
[12:16:17] Error in plugin 'run-sequence'
Message:
    An error occured in task "ts".
```
