### ISSUE TITLE
version 1.0.2 Unexpected identifier error

### ISSUE THREAD

**Issue by or9400** [OverZealous/run-sequence#91]
Hi,

We are getting an error while running a run-sequence.
Version used until now 1.0.2.

The command we run:
```
var runSequence = require('run-sequence');
runSequence('clean', '....', '....');
```

The error:
```
[ERROR] 
[ERROR] react/node_modules/run-sequence/node_modules/chalk/index.js:54
[ERROR] for (const key of Object.keys(ansiStyles)) {
[ERROR]                ^^
[ERROR] SyntaxError: Unexpected identifier
[ERROR]     at Module._compile (module.js:439:25)
[ERROR]     at Object.Module._extensions..js (module.js:474:10)
[ERROR]     at Module.load (module.js:356:32)
[ERROR]     at Function.Module._load (module.js:312:12)
[ERROR]     at Module.require (module.js:364:17)
[ERROR]     at require (module.js:380:17)
[ERROR]     at Object.<anonymous> /react/node_modules/run-sequence/index.js:5:14)
[ERROR]     at Module._compile (module.js:456:26)
[ERROR]     at Object.Module._extensions..js (module.js:474:10)
[ERROR]     at Module.load (module.js:356:32)
```

after changing to 2.0.0 it looks ok.

**Comment by OverZealous** [comment]
Chalk made backwards-incompatible changes, and run-sequence didn't specify the version of Chalk in use (which was a mistake).

I released a versions v2.0.0 to correct this, as you mentioned above.
