### ISSUE TITLE
Getting error because of Dependent module chalk 

### ISSUE THREAD

**Issue by jogendrajangid1** [OverZealous/run-sequence#94]
Hi Team,
We are getting an error because of the latest version of module chalk.  it is working fine on chalk 1.1.x version. can you please suggest an alternate solution for this or make changes to run-sequence to use a specific version of chalk.
chalk/index.js:2
const escapeStringRegexp = require('escape-string-regexp');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (xxxxxxxxx/node_modules/run-sequence/index.js:5:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)"

**Comment by OverZealous** [comment]
This has already been fixed, you need to upgrade to v2 of the library.
